---
ID: "ac65a86a-f83e-500b-b86a-8e2370485279"
Parent: "c061db90-0f0a-577b-bc69-1dde4da19ad5"
Template: "c061db90-0f0a-577b-bc69-1dde4da19ad5"
Path: "/sitecore/templates/Project/jss-nextjs-storybook/Styleguide-FieldUsage-File/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210906T013249Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8ac95c42-fc2e-4050-b7f3-1003685308a6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210906T013249Z
