---
ID: "ccc6d31c-47d8-577f-8d2b-faf94666eaf8"
Parent: "68ff4c78-7f8e-52e2-a491-6bc0cd509f54"
Template: "68ff4c78-7f8e-52e2-a491-6bc0cd509f54"
Path: "/sitecore/templates/Project/jss-nextjs-storybook/Styleguide-FieldUsage-Custom/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210906T013248Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "55f89aee-14c8-460e-abf9-d02eb6c2031f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210906T013248Z
