---
ID: "32fcd996-e156-52e8-94c1-031fb1ed7846"
Parent: "602e0def-2850-5ce6-9bb2-4c57165b4a38"
Template: "602e0def-2850-5ce6-9bb2-4c57165b4a38"
Path: "/sitecore/templates/Project/jss-nextjs-storybook/ExampleCustomRouteType/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210906T013245Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6cfd049-1fe3-4fd6-a9ed-ac5f9819834f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210906T013245Z
