name: MAGICAL - Setup and run Docker locally

on:
  workflow_dispatch:
    inputs:
      REGISTRY:
        description: 'Registry name'     
        required: false
        default: ''
      SITECORE_VERSION: 
        type: choice 
        description: 'Select sitecore windows version'
        options:
        - 10.1-ltsc2019
        - 10.1-2009
        - 10.2-ltsc2019
        - 10.2-2009  
      ISOLATION:
        type: choice 
        description: 'Select isolation type'
        options:
        - default
        - process
      HOST_LICENSE_FOLDER:
        description: 'Path to your Sitecore license'     
        required: true
        default: 'C:\license\license.xml'       
      SQL_SA_PASSWORD: 
        description: 'Password to SQL'
        required: true
        default: 'DsB4j9MB8Ah15OkCLPp'   
      SITECORE_ADMIN_PASSWORD: 
        description: 'Password to Sitecore admin'
        required: true
        default: 'b'
      ID_CLI_SECRET: 
        description: 'Secret for auto login to CM'
        required: true
        default: 'secret_hush_hush'  
      BUILD_CONFIGURATION: 
        type: choice 
        description: 'Debug or release'
        options:
        - debug
        - release
      POPULATE_SOLR_SCHEMA:
        type: boolean 
        description: 'Populate solr schema'
        default: true  
      PUSH_SITECORE_ITEMS:
        type: boolean 
        description: 'Push sitecore items'
        default: true
        
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-run:
    name: Test run  
      
    runs-on: magical
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
